version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 13306:13306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: 'redis:latest'
    ports:
      - 16379:16379
