// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsRoleResourceRelation = "ums_role_resource_relation"

// UmsRoleResourceRelation 后台角色资源关系表
type UmsRoleResourceRelation struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID     int64 `gorm:"column:role_id;comment:角色ID" json:"role_id"`         // 角色ID
	ResourceID int64 `gorm:"column:resource_id;comment:资源ID" json:"resource_id"` // 资源ID
}

// TableName UmsRoleResourceRelation's table name
func (*UmsRoleResourceRelation) TableName() string {
	return TableNameUmsRoleResourceRelation
}
