// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsAdminLoginLog = "ums_admin_login_log"

// UmsAdminLoginLog 后台用户登录日志表
type UmsAdminLoginLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdminID    int64     `gorm:"column:admin_id" json:"admin_id"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	IP         string    `gorm:"column:ip" json:"ip"`
	Address    string    `gorm:"column:address" json:"address"`
	UserAgent  string    `gorm:"column:user_agent;comment:浏览器登录类型" json:"user_agent"` // 浏览器登录类型
}

// TableName UmsAdminLoginLog's table name
func (*UmsAdminLoginLog) TableName() string {
	return TableNameUmsAdminLoginLog
}
