// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsMemberLoginLog = "ums_member_login_log"

// UmsMemberLoginLog 会员登录记录
type UmsMemberLoginLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MemberID   int64     `gorm:"column:member_id" json:"member_id"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	IP         string    `gorm:"column:ip" json:"ip"`
	City       string    `gorm:"column:city" json:"city"`
	LoginType  int32     `gorm:"column:login_type;comment:登录类型：0->PC；1->android;2->ios;3->小程序" json:"login_type"` // 登录类型：0->PC；1->android;2->ios;3->小程序
	Province   string    `gorm:"column:province" json:"province"`
}

// TableName UmsMemberLoginLog's table name
func (*UmsMemberLoginLog) TableName() string {
	return TableNameUmsMemberLoginLog
}
