// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsAdminRoleRelation = "ums_admin_role_relation"

// UmsAdminRoleRelation 后台用户和角色关系表
type UmsAdminRoleRelation struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdminID int64 `gorm:"column:admin_id" json:"admin_id"`
	RoleID  int64 `gorm:"column:role_id" json:"role_id"`
}

// TableName UmsAdminRoleRelation's table name
func (*UmsAdminRoleRelation) TableName() string {
	return TableNameUmsAdminRoleRelation
}
