// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsRolePermissionRelation = "ums_role_permission_relation"

// UmsRolePermissionRelation 后台用户角色和权限关系表
type UmsRolePermissionRelation struct {
	ID           int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID       int64 `gorm:"column:role_id" json:"role_id"`
	PermissionID int64 `gorm:"column:permission_id" json:"permission_id"`
}

// TableName UmsRolePermissionRelation's table name
func (*UmsRolePermissionRelation) TableName() string {
	return TableNameUmsRolePermissionRelation
}
