// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsRoleMenuRelation = "ums_role_menu_relation"

// UmsRoleMenuRelation 后台角色菜单关系表
type UmsRoleMenuRelation struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID int64 `gorm:"column:role_id;comment:角色ID" json:"role_id"` // 角色ID
	MenuID int64 `gorm:"column:menu_id;comment:菜单ID" json:"menu_id"` // 菜单ID
}

// TableName UmsRoleMenuRelation's table name
func (*UmsRoleMenuRelation) TableName() string {
	return TableNameUmsRoleMenuRelation
}
