// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUmsResourceCategory = "ums_resource_category"

// UmsResourceCategory 资源分类表
type UmsResourceCategory struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"` // 创建时间
	Name       string    `gorm:"column:name;comment:分类名称" json:"name"`               // 分类名称
	Sort       int32     `gorm:"column:sort;comment:排序" json:"sort"`                 // 排序
}

// TableName UmsResourceCategory's table name
func (*UmsResourceCategory) TableName() string {
	return TableNameUmsResourceCategory
}
