// Code generated by Kitex v0.9.1. DO NOT EDIT.

package useradminservice

import (
	server "github.com/cloudwego/kitex/server"
	user_admin "github.com/yqihe/91-mall/gomall/rpc_gen/kitex_gen/user-admin"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler user_admin.UserAdminService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
